### ISSUE TITLE
Doesn't work in Windows 10 IE11

### ISSUE THREAD

**Issue by stevengrimaldo** [constancecchen/object-fit-polyfill#44] opened 2019-02-22 23:31 UTC
I opened your demo page in BrowserStack using Windows 10 - IE11 and compared it to your demo page in Mac Mojave - Latest Chrome and they aren't matching leading me to believe it does NOT work in IE as mentioned.

Please help.

**Comment by andrejpavlovic** [comment] 2019-02-26 23:26
It works fine in IE11, just opened it myself.

**Comment by lyssar** [comment] 2019-03-29 08:30
Well I can confirm that at least object-fit cover does indeed not work in IE11 apparently.
![E11 - Win7_29_03_2019_09_24_53](https://user-images.githubusercontent.com/814001/55219498-54a62700-5205-11e9-8b9c-b85012cb0e6c.png)

As you can see the dog in the lower right corner should be cover the complete div but it doesn't

**Comment by rohermez** [comment] 2019-03-31 03:07
It isn't working for me too on IE11 Windows

**Comment by cee-chen** [comment] 2019-03-31 05:49
Hey, sorry for the delay on this one. As others commented: this is working fine on my native Windows 10 device in IE11. Here is what the 4 skyscraper photos should look like:

<img width="1018" alt="" src="https://user-images.githubusercontent.com/549407/55285264-3e02eb80-533d-11e9-85fe-35ff26af56b2.png">

It looks exactly the same on IE 11 as it does on my Mac Mojave on Chrome. I'm going to close this as can't reproduce, unless you can send a screenshot of what your IE 11 skyscrapers and Chrome skyscrapers next to each other looking differently.

@cefuroX, thanks for the screenshot! The dog in the low right corner is an issue with the video source I'm using to link - not an issue with the polyfill (otherwise, the 4 skyscrapers wouldn't be rendering the way that they do). It appears the video source frequently changes or gets moved around which is causing the issue. I need to upload my own mp4 file at some point instead of reusing someone else's (sorry to the fine folks at Coverr for doing so).

**Closed as completed by cee-chen** 2019-03-31 05:49 UTC
